export const items = [
    {
      id: '1',
      title: 'Yerba mate je plná živín',
      backgroundColor: '#5DBCD2',
      description: 'Yerba mate prirodzene obsahuje takmer všetky mikroživiny potrebné ľudským telom. Pravidelné pitie mate zlepší váš imunitný systém vo všeobecnosti, detoxikuje vaše telo a zabráni mnohým chorobám. Okrem antioxidantov a polyfenolov je yerba mate bohatá na minerály, aminokyseliny a esenciálne vitamíny. Vitamíny obsiahnuté v Yerba Mate sú hlavne z B-komplexu, ktorý obsahuje 8 z 13 základných vitamínov potrebných pre optimálne fungovanie DNA, obnovu buniek a metabolickú účinnosť tukov a bielkovín. Obsahuje tiež dôležité minerály, ako je draslík a horčík, ktoré zlepšujú funkciu srdca, medzi mnohými ďalšími výhodami. Obsahuje chlorofyl, fytonutrienty, triesloviny, stopové prvky a flavonoidy, ktoré pridávajú ďalšie vlastnosti a zdravotné prínosy. Jeho obsah kofeínu je kompenzovaný teobromínom a teofylínom; pôsobí na centrálny nervový systém so silným účinkom, ktorý je energizujúci a regeneračný zároveň pre myseľ a telo. V skutočnosti yerba mate spĺňa všetky požiadavky, ktoré sa majú považovať za superpotravinu: má silný vplyv na zdravie; predstavuje bohatý zdroj vitamínov a minerálov; a má mnoho fytonutrientov a fytochemikálií, ako sú antioxidanty, detoxikačné činidlá, fytoestrogény a bunkové regulátory. Yerba mate, s viac antioxidantov ako zelený čaj, je považovaný za jeden z najlepších nápojov na svete.'
    },
    {
      id: '2',
      title: 'Yerba mate zabraňuje chorobám',
      backgroundColor: '#814A0E',
      description: 'Pravidelné pitie čaju Mate môže zabrániť a dokonca zvrátiť diabetes typu 2. Štúdia vykonaná u diabetických a preddiabetických pacientov ukázala, že infúzia yerba mate pomáha kontrolovať lipidy a hladinu cukru v krvi; a v kombinácii so správnou stravou je yerba mate vysoko účinný pri znižovaní "zlých" hladín cholesterolu a triglyceridov u pacientov s pred diabetikou; znižuje riziko vzniku ischemárnej choroby srdca. Tým, že zabraňuje hromadeniu zlého cholesterolu a triglyceridov v tepnách, yerba mate tiež znižuje riziko artériosklerózy a kardiovaskulárnych ochorení a zároveň zvyšuje HDL cholesterol, známy ako "dobrý cholesterol", čím sa znižuje riziko srdcových ochorení. Polyfenoly v Yerba Mate tiež chránia tkanivo myokardu a zabraňujú bunkovej smrti spôsobenej obmedzením prietoku krvi. Niektoré zlúčeniny v Yerba mate, ako je teobromín a kyselina chlorogenová, majú lepšie neuroprotektívne vlastnosti ako kofeín a nikotín, čo naznačuje, že yerba mate by mohol obsahovať kľúč nielen na prevenciu Parkinsonovej choroby, ale aj na vývoj liečby v budúcnosti. Napriek tomu, že zvyk piť mate nestačí na prevenciu osteoporózy, má ochranný účinok na kosti a pomáha udržiavať hustotu kostí, podľa niekoľkých štúdií. Tým, že zabraňuje poškodeniu červených krviniek kyslíkom (proces známy ako oxidačný stres), pitie 1 litra čaju mate denne môže tiež zabrániť chorobám, ktoré vyplývajú z tohto procesu, ako je Alzheimerova choroba.',
    },
    {
      id: '3',
      title: 'Yerba mate je antioxidant',
      backgroundColor: '#959684',
      description: 'Infúzia yerba mate vo svojej tradičnej forme je silný antioxidant, ktorý prekonáva červené víno, zelený čaj, čierny čaj a pomarančový džús. S vysokým obsahom polyfenolov (chlorogénnych a galových kyselín) je yerba mate schopný obnoviť bunkovú rovnováhu a pôsobiť proti škodlivému účinku voľných radikálov, ktoré urýchľujú proces starnutia a vývoj chronických ochorení. Samotná prítomnosť polyfenolov v potravinách alebo nápojoch však nezaručuje, že môžu byť úplne asimilované telom. Aké je tajomstvo veľkej antioxidačnej sily yerba mate? Podľa niekoľkých štúdií v priebehu rokov to môže byť spôsobené spôsobom, akým pijeme mate: pridaním horúcej vody (jej tradičný prípravok) sa všetky antioxidanty účinne extrahujú. Inými slovami, aj keď existujú aj iné spôsoby, ako piť mate ako studené voda (nazývané "tereré") a varené mate (v čajových vrecúškach), ten, ktorý môže obsahovať až o 90% viac antioxidantov ako slávny zelený čaj, je tradičný horúci čaj, kde sa používa najväčšie množstvo yerba mate. Ďalším faktorom, ktorý výrazne ovplyvňuje antioxidačné vlastnosti Yerba Mate, je pridanie prírodných bylín, ako je mäta, pennyroyal, mäta pieporná a citrónový balzam, ktoré pridávajú svoje liečivé vlastnosti k vlastnostiam Yerba Mate, čím sa zvyšuje antioxidačný účinok. Antioxidanty zlepšujú prirodzenú obranyschopnosť tela a zabraňujú zhoršeniu buniek, často urýchľované stresom každodenného života a nadbytkom voľných radikálov. To je dôvod, prečo yerba mate zvyšuje samoochrannú a preventívnu kapacitu tých, ktorí ju pijú.'
    },
    {
      id: '4',
      title: 'Yerba mate reguluje cholesterol a pomáha zlepšovať krvný tlak',
      backgroundColor: '#959684',
      description: 'Mnohé štúdie ukázali, že yerba mate, ak sa konzumuje denne, zlepšuje kardiovaskulárne zdravie znížením hladiny cholesterolu medzi 15% a 18%, čo môže zabrániť chorobám, ako je artérioskleróza. Má tiež mierny hypotenzívny a vazodilatačný účinok, ktorý môže byť prospešný pre ľudí s vysokým krvným tlakom. Je to preto, že yerba mate zvyšuje aktivitu kardioochranných zlúčenín nazývaných saponíny, ktoré prispievajú k schopnosti tela znižovať LDL cholesterol (tiež známy ako "zlý cholesterol") oveľa rýchlejšie ako zvyčajne. Na druhej strane saponíny zvyšujú HDL cholesterol, známy ako "dobrý cholesterol", čím zabraňujú kardiovaskulárnym ochoreniam. Telo potrebuje cholesterol na vytvorenie zdravých buniek. Ale keď v krvi cirkuluje príliš veľa cholesterolu, stáva sa to oxidované a hromadí sa do tukových usadenín, ktoré upchávajú tepny, čím sa zvyšuje riziko určitých ochorení, ako je artérioskleróza a iné kardiovaskulárne stavy. Antioxidačná sila polyfenolov, ako aj účinok vitamínu C, horčíka a mangánu obsiahnutého v yerba mate, znižujú oxidáciu cholesterolu a zabraňujú jeho hromadeniu v tepnách, pôsobia ako hypotenzívne vazodilatačné činidlo a prispievajú k kardiovaskulárnemu zdraviu. Preto, okrem zdravej výživy a cvičenia, vrátane yerba mate vo vašom každodennom živote je vynikajúci prirodzený spôsob, ako znížiť hladinu zlého cholesterolu.'
    },
    {
      id: '5',
      title: 'Yerba mate zlepšuje trávenie',
      backgroundColor: '#959684',
      description: 'Pitie mate čaju zlepšuje trávenie tým, že stimuluje pohyb čriev, ako aj tok žlče a tráviacich štiav. Yerba mate je vynikajúci spojenec na zmiernenie zápchy, pokiaľ tiež pijete 2 litre vody denne. Okrem poskytovania dobrého príjmu tekutín, ktorý tiež pomáha tráviacemu systému, je preukázaným faktom účinok yerba mate na črevnú aktivitu. Funguje tak, že stimuluje kontrakcie a pohyby v gastrointestinálnom systéme (preto má niekedy yerba mate mierny laxatívny účinok). Táto výhoda sa zvyšuje, keď pridáme tráviace byliny do čaju nášho partnera, najčastejšie sa používajú púpavy (tráviace, antioxidačné, protizápalové a diuretické), šalvia (tráviace, antibiotikum, adstringentné, antioxidačné a relaxačné), rozmarín (zažívací, čistiaci, stimulujúci), pennyroyálne (tráviace, afrodiziakum a upokojujúce počas menštruačného nepohodlia) a mäta (tráviace, analgetické, protizápalové). Takže neváhajte vytvoriť si vlastnú infúziu yerba mate a pridať niektoré z týchto bylín. Je tiež dobré kombinovať svojich mate s potravinami s vysokým obsahom vlákniny. Medzi najlepšie občerstvenie na jedenie s čajom a zlepšenie trávenia patria čerstvé ovocie, ako sú jablká, ananás, pomaranče (môžete dokonca pridať niekoľko plátkov do infúzie); tyče a orechy s vysokým obsahom vlákniny. Vďaka zvýšeniu energie vám yerba mate tiež umožňuje sledovať zdravé návyky, ktoré zlepšujú tráviaci systém, ako je cvičenie a cvičenie športu.'
    },
    {
      id: '6',
      title: 'Yerba mate má prirodzený energizujúci účinok',
      backgroundColor: '#959684',
      description: 'Vďaka obsahu kofeínu (niekedy označovanému ako "mateína") yerba mate zvyšuje energiu a zameranie a uprednostňuje lepší výkon v každodenných činnostiach, ktoré vyžadujú koncentráciu a bdelosť, ako je štúdium, práca alebo fyzické aktivity. Aj keď účinok je podobný účinku kávy; A aj keď obaja majú relatívne rovnaké množstvo kofeínu, proces stimulácie je iný. Niekedy môže byť účinok kávy príliš silný; zatiaľ čo yerba mate "prebúdza" ľudí postupným a príjemným spôsobom. Môže to byť preto, že kofeín v yerba mate sa zriedi vo väčšom množstve vody, ktorá sa neskôr opije dúškom. Mate je tiež výrazne zdravší ako komerčné energetické nápoje a hypertonické nápoje, pretože majú vysokú koncentráciu látok, ako je kofeín (niekedy majú toľko kofeínu, že môžu spôsobiť nespavosť a nervozitu) cukor (až 10%), farbivá, sacharidy a elektrolyty. Yerba mate, na druhej strane, je prírodný nápoj a jeho energizujúci účinok pochádza zo samotnej prírody, nie z umelého procesu. Mate tiež prináša do tela nespočetné výhody, zatiaľ čo tieto komerčné nápoje, aj keď nie sú toxické, tiež nepridŕšili veľkú hodnotu. Mate, ako veľmi špeciálny zdroj energie, stimuluje neuróny a podporuje mozgovú aktivitu, vedomé vedomie, pamäť a uvažovanie. Obsahuje tiež iné xantíny, teobromín a teofylín, ktorých relaxačné účinky pomáhajú regulovať všetky telesné systémy. Takže sa zdá, že regeneračný účinok yerba mate na myseľ a telo je lepší ako iné nápoje obsahujúce kofeín; pretože má dvojitý účinok, ktorý je stimulujúci a relaxačný zároveň. Pitie čaju po celý deň môže byť energizujúce a stimulujúce, ale aj upokojujúce. A hoci yerba mate poskytuje fyzickú energiu a pozdvihuje vašich duchov; To nemá vplyv na kvalitu vášho spánku a odpočinku.'
    },
    {
      id: '7',
      title: 'Yerba mate čistí vaše telo',
      backgroundColor: '#959684',
      description: 'Yerba mate má tiež diuretický a mierne laxatívny účinok, pretože znižuje retenciu tekutín a zlepšuje funkciu obličiek. To pomáha telu eliminovať toxíny a čistiť sa prirodzene. Tento diuretický účinok je úplne prirodzený. Yerba mate inhibuje antidiuretický hormón, tiež známy ako arginín vazopresín (AVP) alebo argipressín; podporuje elimináciu moču. To by však malo byť vyvážené zdravou konzumáciou 2 litre vody denne, aby sa telo hydratovalo. Yerba mate tiež stimuluje pohyb čriev a pomáha telu v jeho prirodzenom procese odstraňovania odpadu a toxínov. To je dôvod, prečo sa odporúča pre ľudí trpiacich zápchou. Táto výhoda môže byť zvýšená pridaním tráviacich bylín do čaju vášho mate a konzumáciou potravín s vysokým obsahom vlákniny. Odborníci sa však zhodujú na tom, že yerba mate v žiadnom prípade nenahrádza minimálny príjem vody odporúčaný každý deň: 2 litre. Takže spolu so súpravou kamarátov nezabudnite mať vždy po ruke pohár vody, aby ste čo najviac vyťažia z yerba mate.'
    },
    {
      id: '8',
      title: 'Yerba mate je ideálny pre šport',
      backgroundColor: '#959684',
      description: 'Yerba mate je cenným zdrojom výhod, ktoré uprednostňujú prax športu; Počnúc dávkou kofeínu, ktorá stimuluje nervový systém a je ideálna pred akoukoľvek fyzickou alebo intelektuálnou aktivitou. Tento nápoj sa odporúča pre športovcov ako alternatívu k komerčným energetickým nápojom. Pred tréningom mate pracuje ako stimulačný nápoj, prirodzenejší ako energetické nápoje a iné športové doplnky. Počas tréningu pomáha mate účinnejšie metabolizovať sacharidy a zabraňuje hromadeniu kyseliny mliečnej v tele; čo sa premieta do väčšieho a lepšieho energie, zvýšenej fyzickej vytrvalosti, menšieho vyhorenia a schopnosti trénovať dlhšie. Ale okrem toho, miera zotavenia po cvičení sa výrazne zvyšuje s yerba mate, podľa štúdie British Journal of Nutrition. Mate zlepšuje motorické zručnosti a má protizápalové účinky po tréningu, najmä pri aktivitách s vysokým dopadom. V skutočnosti niektorí hovoria, že yerba mate je tajomstvom úspechu niektorých uznávaných futbalistov z národných tímov Uruguaja, Argentíny a Paraguaja, vrátane hviezd ako Leo Messi a Luis Suarez, ktorí pravidelne pijú čaj. Yerba mate im dodáva energiu a zlepšuje ich celkovú fyzickú kondíciu, čo vedie k lepšiemu výkonu na ihrisku.'
    },
    {
      id: '9',
      title: 'Yerba mate vám pomôže udržať si zdravú váhu',
      backgroundColor: '#959684',
      description: 'Okrem toho, že má nulový tuk a takmer žiadny sodík, yerba mate má veľmi nízky obsah kalórií, takže môže byť ľahko zahrnutý do akejkoľvek stravy a do rutiny každého, kto sa snaží kontrolovať svoju váhu alebo jesť zdravo. Ako diuretická a čistiaca infúzia, mate čaj zabraňuje prírastku hmotnosti v dôsledku zadržiavania tekutín a zároveň podporuje elimináciu toxínov. To tiež zvyšuje váš metabolizmus a pomáha vám spáliť viac kalórií, najmä keď vykonávate fyzické aktivity (pre ktoré, mimochodom, yerba mate poskytuje energiu, ktorú potrebujete). Hoci yerba mate by nemala byť náhradou za jedlo; je pravda, že pitie mate produkuje sýtosť a znižuje chuť do jedla vo všeobecnosti; ktoré môžu prispieť k úbytku hmotnosti. A tým, že má pozitívny vplyv na náladu, môže tiež zabrániť tomu, čo je známe ako "emocionálna chuť do jedla" alebo hlad spôsobený stresom. Ale to, čo robí yerba mate dokonalým doplnkom zdravého životného štýlu, sú jeho viaceré výživové vlastnosti; ktorý, viac ako len chudnutie, pomáha udržiavať dlhotrvajúci stav pohody. Zdravotné prínosy Yerba mate sú tak výhodné, že jeho pravidelné pitie sa dôrazne odporúča zostať vo forme fyzicky, psychicky a emocionálne. V skutočnosti, pre tých, ktorí radi sledujú svoj osobný vzhľad vo všeobecnosti, je yerba mate vynikajúcim spojencom v ich estetickej rutine. Má vynikajúce vlastnosti pre pokožku a vlasy. Existujú šampóny, oleje, krémy, mydlá a dokonca aj kúpeľové soli vyrobené z extraktu yerba mate.'
    },
    {
      id: '10',
      title: 'Yerba mate je antidepresívum',
      backgroundColor: '#8F986D',
      description: 'Yerba mate má tiež pozitívny vplyv na duševné a emocionálne zdravie a považuje sa za akýsi prírodný antidepresívum. To je dôvod, prečo má povesť "dobrého spoločníka" kedykoľvek počas dňa. Pitie mate ráno, napríklad, zaručuje motiváciu a energiu pre deň vďaka obsahu kofeínu. Táto energia poskytovaná yerba mate je však šetrná k mysli a telu bez nepríjemných vedľajších účinkov. A pretože pijeme čaj pomaly, táto energia je postupne asimilovaná telom. Na rozdiel od iných nápojov, ako je káva, čaj alebo komerčné energetické nápoje; Pitie čaju má veľmi malý vplyv na váš spánkový cyklus, takže zvyčajne nespôsobuje nespavosť. Okrem toho je mate tradične zdieľaný s rodinou, priateľmi a kolegami v pitných kolách nazývaných "mateadas", najmä v Argentíne. Perfektný rituál na vytvorenie pekných spomienok so svojimi blízkymi a zároveň na podporu zdravého spoločenského života.'
    }
  ];
  
  export const openSpring = { type: 'spring', stiffness: 200, damping: 30 };
  